// data.js
const postcardData = [
  {
    "id": "PHCNSC-1542",
    "type": "寄出",
    "country": "中国",
    "region": "湖北武汉",
    "note": "",
    "tags": [],
    "imgFront": "./images/PHCNSC-1542图像面.jpg",
    "sendDate": "2026-01-10",
    "receiveDate": "2026-01-12",
    "person": "Silence",
    "platform": "Post-Hi"
  },
  {
    "id": "PHCNSC-1536",
    "type": "寄出",
    "country": "中国",
    "region": "山东济南",
    "note": "",
    "tags": [],
    "imgFront": "./images/PHCNSC-1536图像面.jpg",
    "sendDate": "2026-01-07",
    "receiveDate": "2026-01-12",
    "person": "汤圆",
    "platform": "Post-Hi"
  },
  {
    "id": "PHCNSC-1535",
    "type": "寄出",
    "country": "中国",
    "region": "上海市闵行区",
    "note": "",
    "tags": [],
    "imgFront": "./images/PHCNSC-1535图像面.jpg",
    "sendDate": "2026-01-07",
    "receiveDate": "2026-01-13",
    "person": "ahy",
    "platform": "Post-Hi"
  },
  {
    "id": "PHCNSC-1534",
    "type": "寄出",
    "country": "中国",
    "region": "辽宁葫芦岛",
    "note": "",
    "tags": [],
    "imgFront": "./images/PHCNSC-1534图像面.jpg",
    "sendDate": "2026-01-07",
    "receiveDate": "2026-01-12",
    "person": "知秋",
    "platform": "Post-Hi"
  },
  {
    "id": "PHCNSC-1532",
    "type": "寄出",
    "country": "中国",
    "region": "辽宁沈阳",
    "note": "",
    "tags": [],
    "imgFront": "./images/PHCNSC-1532图像面.jpg",
    "sendDate": "2026-01-05",
    "receiveDate": "2026-01-06",
    "person": "波本本",
    "platform": "Post-Hi"
  },
  {
    "id": "PHCNSC-1531",
    "type": "寄出",
    "country": "中国",
    "region": "广东深圳",
    "note": "",
    "tags": [],
    "imgFront": "./images/PHCNSC-1531图像面.jpg",
    "sendDate": "2026-01-05",
    "receiveDate": "2026-01-11",
    "person": "坡坡",
    "platform": "Post-Hi"
  },
  {
    "id": "PHCNSC-1530",
    "type": "寄出",
    "country": "中国",
    "region": "浙江金华",
    "note": "",
    "tags": [],
    "imgFront": "./images/PHCNSC-1530图像面.jpg",
    "sendDate": "2026-01-05",
    "receiveDate": "2026-01-09",
    "person": "爬上树的猴",
    "platform": "Post-Hi"
  },
  {
    "id": "PHCNSC-1529",
    "type": "寄出",
    "country": "中国",
    "region": "江苏苏州",
    "note": "",
    "tags": [],
    "imgFront": "./images/PHCNSC-1529图像面.jpg",
    "sendDate": "2026-01-05",
    "receiveDate": "2026-01-09",
    "person": "倥~",
    "platform": "Post-Hi"
  },
  {
    "id": "PHCNSC-1528",
    "type": "寄出",
    "country": "中国",
    "region": "湖北武汉",
    "note": "",
    "tags": [],
    "imgFront": "./images/PHCNSC-1528图像面.jpg",
    "sendDate": "2026-01-05",
    "receiveDate": "2026-01-08",
    "person": "Silence",
    "platform": "Post-Hi"
  },
  {
    "id": "PHCNSC-1526",
    "type": "寄出",
    "country": "中国",
    "region": "湖北武汉",
    "note": "",
    "tags": [],
    "imgFront": "./images/PHCNSC-1526图像面.jpg",
    "sendDate": "2026-01-05",
    "receiveDate": "2026-01-13",
    "person": "偷闲馆",
    "platform": "Post-Hi"
  },
  {
    "id": "PHCNSC-1525",
    "type": "寄出",
    "country": "中国",
    "region": "浙江金华",
    "note": "",
    "tags": [],
    "imgFront": "./images/PHCNSC-1525图像面.jpg",
    "sendDate": "2026-01-05",
    "receiveDate": "2026-01-09",
    "person": "爬上树的猴",
    "platform": "Post-Hi"
  },
  {
    "id": "PHCNSC-1524",
    "type": "寄出",
    "country": "中国",
    "region": "福建福州",
    "note": "",
    "tags": [],
    "imgFront": "./images/PHCNSC-1524图像面.jpg",
    "sendDate": "2026-01-05",
    "receiveDate": "2026-01-08",
    "person": "咕啾",
    "platform": "Post-Hi"
  },
  {
    "id": "PHCNSC-1523",
    "type": "寄出",
    "country": "中国",
    "region": "山东济南",
    "note": "",
    "tags": [],
    "imgFront": "./images/PHCNSC-1523图像面.jpg",
    "sendDate": "2026-01-05",
    "receiveDate": "2026-01-07",
    "person": "汤圆",
    "platform": "Post-Hi"
  },
  {
    "id": "PHCNSC-1481",
    "type": "寄出",
    "country": "中国",
    "region": "河北石家庄",
    "note": "",
    "tags": [],
    "imgFront": "./images/PHCNSC-1481图像面.jpg",
    "sendDate": "2025-12-25",
    "receiveDate": "2025-12-29",
    "person": "JohnClark",
    "platform": "Post-Hi"
  },
  {
    "id": "PHCNSC-1474",
    "type": "寄出",
    "country": "中国",
    "region": "浙江金华",
    "note": "",
    "tags": [],
    "imgFront": "./images/PHCNSC-1474图像面.jpg",
    "sendDate": "2025-12-22",
    "receiveDate": "2025-12-25",
    "person": "爬上树的猴",
    "platform": "Post-Hi"
  },
  {
    "id": "PHCNSC-1473",
    "type": "寄出",
    "country": "中国",
    "region": "浙江金华",
    "note": "",
    "tags": [],
    "imgFront": "./images/PHCNSC-1473图像面.jpg",
    "sendDate": "2025-12-22",
    "receiveDate": "2025-12-25",
    "person": "爬上树的猴",
    "platform": "Post-Hi"
  },
  {
    "id": "PHCNSC-1462",
    "type": "寄出",
    "country": "中国",
    "region": "福建福州",
    "note": "",
    "tags": [],
    "imgFront": "./images/PHCNSC-1462图像面.jpg",
    "sendDate": "2025-12-20",
    "receiveDate": "2025-12-26",
    "person": "月儿丫丫",
    "platform": "Post-Hi"
  },
  {
    "id": "PHCNSC-1461",
    "type": "寄出",
    "country": "中国",
    "region": "福建厦门",
    "note": "",
    "tags": [],
    "imgFront": "./images/PHCNSC-1461图像面.jpg",
    "sendDate": "2025-12-20",
    "receiveDate": "2026-01-11",
    "person": "学徒",
    "platform": "Post-Hi"
  },
  {
    "id": "PHCNSC-1460",
    "type": "寄出",
    "country": "中国",
    "region": "四川德阳",
    "note": "",
    "tags": [],
    "imgFront": "./images/PHCNSC-1460图像面.jpg",
    "sendDate": "2025-12-20",
    "receiveDate": "2026-01-06",
    "person": "Golgental",
    "platform": "Post-Hi"
  },
  {
    "id": "PHCNSC-1459",
    "type": "寄出",
    "country": "中国",
    "region": "上海市浦东新区",
    "note": "",
    "tags": [],
    "imgFront": "./images/PHCNSC-1459图像面.jpg",
    "sendDate": "2025-12-20",
    "receiveDate": "2025-12-22",
    "person": "廉乐",
    "platform": "Post-Hi"
  },
  {
    "id": "PHCNSC-1453",
    "type": "寄出",
    "country": "中国",
    "region": "广东中山",
    "note": "",
    "tags": [],
    "imgFront": "./images/PHCNSC-1453图像面.jpg",
    "sendDate": "2025-12-20",
    "receiveDate": "2025-12-28",
    "person": "CAI",
    "platform": "Post-Hi"
  },
  {
    "id": "PHCNSC-1452",
    "type": "寄出",
    "country": "中国",
    "region": "上海市虹口区",
    "note": "",
    "tags": [],
    "imgFront": "./images/PHCNSC-1452图像面.jpg",
    "sendDate": "2025-12-20",
    "receiveDate": "2025-12-22",
    "person": "嵇尔",
    "platform": "Post-Hi"
  },
  {
    "id": "PHCNSC-1450",
    "type": "寄出",
    "country": "中国",
    "region": "湖南长沙",
    "note": "",
    "tags": [],
    "imgFront": "./images/PHCNSC-1450图像面.jpg",
    "sendDate": "2025-12-15",
    "receiveDate": "2025-12-21",
    "person": "90后的骏",
    "platform": "Post-Hi"
  },
  {
    "id": "PHCNSC-1449",
    "type": "寄出",
    "country": "中国",
    "region": "北京市朝阳区",
    "note": "",
    "tags": [],
    "imgFront": "./images/PHCNSC-1449图像面.jpg",
    "sendDate": "2025-12-15",
    "receiveDate": "2025-12-17",
    "person": "王杰",
    "platform": "Post-Hi"
  },
  {
    "id": "PHCNSC-1448",
    "type": "寄出",
    "country": "中国",
    "region": "河北沧州",
    "note": "",
    "tags": [],
    "imgFront": "./images/PHCNSC-1448图像面.jpg",
    "sendDate": "2025-12-15",
    "receiveDate": "2025-12-17",
    "person": "慕夏",
    "platform": "Post-Hi"
  },
  {
    "id": "PHCNSC-1447",
    "type": "寄出",
    "country": "中国",
    "region": "湖北武汉",
    "note": "",
    "tags": [],
    "imgFront": "./images/PHCNSC-1447图像面.jpg",
    "sendDate": "2025-12-15",
    "receiveDate": "2025-12-23",
    "person": "caia97",
    "platform": "Post-Hi"
  },
  {
    "id": "PHCNSC-1446",
    "type": "寄出",
    "country": "中国",
    "region": "广东深圳",
    "note": "",
    "tags": [],
    "imgFront": "./images/PHCNSC-1446图像面.jpg",
    "sendDate": "2025-12-15",
    "receiveDate": "2025-12-18",
    "person": "坡坡",
    "platform": "Post-Hi"
  },
  {
    "id": "PHCNSC-1437",
    "type": "寄出",
    "country": "中国",
    "region": "福建厦门",
    "note": "",
    "tags": [],
    "imgFront": "./images/PHCNSC-1437图像面.jpg",
    "sendDate": "2025-12-11",
    "receiveDate": "2025-12-14",
    "person": "Doris2016",
    "platform": "Post-Hi"
  },
  {
    "id": "PHCNSC-1424",
    "type": "寄出",
    "country": "中国",
    "region": "辽宁抚顺",
    "note": "",
    "tags": [],
    "imgFront": "./images/PHCNSC-1424图像面.jpg",
    "sendDate": "2025-12-08",
    "receiveDate": "2025-12-10",
    "person": "Cathy",
    "platform": "Post-Hi"
  },
  {
    "id": "PHCNZJ-6225",
    "type": "收到",
    "country": "中国",
    "region": "浙江金华",
    "note": "",
    "tags": [],
    "imgFront": "./images/PHCNZJ-6225图像面.jpg",
    "sendDate": "2026-01-10",
    "receiveDate": "2026-01-14",
    "person": "爬上树的猴",
    "platform": "Post-Hi"
  },
  {
    "id": "PHCNZJ-5928",
    "type": "收到",
    "country": "中国",
    "region": "浙江金华",
    "note": "",
    "tags": [],
    "imgFront": "./images/PHCNZJ-5928图像面.jpg",
    "sendDate": "2025-12-23",
    "receiveDate": "2026-01-04",
    "person": "爬上树的猴",
    "platform": "Post-Hi"
  },
  {
    "id": "PHCNZJ-5911",
    "type": "收到",
    "country": "中国",
    "region": "浙江萧山",
    "note": "",
    "tags": [],
    "imgFront": "./images/PHCNZJ-5911图像面.jpg",
    "sendDate": "2025-12-21",
    "receiveDate": "2026-01-04",
    "person": "orangesoda",
    "platform": "Post-Hi"
  },
  {
    "id": "PHCNZJ-5823",
    "type": "收到",
    "country": "中国",
    "region": "浙江金华",
    "note": "",
    "tags": [],
    "imgFront": "./images/PHCNZJ-5823图像面.jpg",
    "sendDate": "2025-12-19",
    "receiveDate": "2025-12-22",
    "person": "爬上树的猴",
    "platform": "Post-Hi"
  },
  {
    "id": "PHCNNM-0464",
    "type": "收到",
    "country": "中国",
    "region": "内蒙古海拉尔",
    "note": "",
    "tags": [],
    "imgFront": "./images/PHCNNM-0464图像面.jpg",
    "sendDate": "2025-12-24",
    "receiveDate": "2026-01-04",
    "person": "云乔",
    "platform": "Post-Hi"
  },
  {
    "id": "PHCNHI-0403",
    "type": "收到",
    "country": "中国",
    "region": "海南深圳",
    "note": "",
    "tags": [],
    "imgFront": "./images/PHCNHI-0403图像面.jpg",
    "sendDate": "2026-01-06",
    "receiveDate": "2026-01-11",
    "person": "坑坑",
    "platform": "Post-Hi"
  },
  {
    "id": "PHCNHE-2084",
    "type": "收到",
    "country": "中国",
    "region": "河北石家庄",
    "note": "",
    "tags": [],
    "imgFront": "./images/PHCNHE-2084图像面.jpg",
    "sendDate": "2025-12-24",
    "receiveDate": "2025-12-25",
    "person": "JohnClark",
    "platform": "Post-Hi"
  },
  {
    "id": "PHCNHB-2404",
    "type": "收到",
    "country": "中国",
    "region": "湖北武汉",
    "note": "",
    "tags": [],
    "imgFront": "./images/PHCNHB-2404图像面.jpg",
    "sendDate": "2026-01-10",
    "receiveDate": "2026-01-12",
    "person": "yinfeng",
    "platform": "Post-Hi"
  },
  {
    "id": "PHCNGD-6532",
    "type": "收到",
    "country": "中国",
    "region": "广东东莞",
    "note": "",
    "tags": [],
    "imgFront": "./images/PHCNGD-6532图像面.jpg",
    "sendDate": "2025-12-21",
    "receiveDate": "2025-12-22",
    "person": "ziyi",
    "platform": "Post-Hi"
  },
  {
    "id": "PHCNGD-6415",
    "type": "收到",
    "country": "中国",
    "region": "广东深圳",
    "note": "",
    "tags": [],
    "imgFront": "./images/PHCNGD-6415图像面.jpg",
    "sendDate": "2025-12-13",
    "receiveDate": "2025-12-17",
    "person": "坡坡",
    "platform": "Post-Hi"
  },
  {
    "id": "PHCNFJ-2614",
    "type": "收到",
    "country": "中国",
    "region": "福建厦门",
    "note": "",
    "tags": [],
    "imgFront": "./images/PHCNFJ-2614图像面.jpg",
    "sendDate": "2025-12-15",
    "receiveDate": "2025-12-22",
    "person": "Doris2016",
    "platform": "Post-Hi"
  },
  {
    "id": "PHCNBJ-2867",
    "type": "收到",
    "country": "中国",
    "region": "北京市东城区",
    "note": "",
    "tags": [],
    "imgFront": "./images/PHCNBJ-2867图像面.jpg",
    "sendDate": "2025-12-21",
    "receiveDate": "2025-12-23",
    "person": "鸠烛",
    "platform": "Post-Hi"
  },
  {
    "id": "SC-002648",
    "type": "寄出",
    "country": "中国",
    "region": "江西九江",
    "note": "",
    "tags": [],
    "imgFront": "./images/SC-002648图像面.jpg",
    "sendDate": "2026-01-08",
    "receiveDate": "2026-01-13",
    "person": "小瑞",
    "platform": "Manyour"
  },
  {
    "id": "SC-002658",
    "type": "寄出",
    "country": "中国",
    "region": "北京房山区",
    "note": "",
    "tags": [],
    "imgFront": "./images/SC-002658图像面.jpg",
    "sendDate": "2026-01-09",
    "receiveDate": "2026-01-13",
    "person": "蜜蜂（糊弄人的拉黑）",
    "platform": "Manyour"
  },
  {
    "id": "SC-002659",
    "type": "寄出",
    "country": "中国",
    "region": "广东清远",
    "note": "",
    "tags": [],
    "imgFront": "./images/SC-002659图像面.jpg",
    "sendDate": "2026-01-09",
    "receiveDate": "2026-01-13",
    "person": "zhu",
    "platform": "Manyour"
  },
  {
    "id": "SC-002578",
    "type": "寄出",
    "country": "中国",
    "region": "广东广州",
    "note": "",
    "tags": [],
    "imgFront": "./images/SC-002578图像面.jpg",
    "sendDate": "2026-01-04",
    "receiveDate": "2026-01-12",
    "person": "一碗粥",
    "platform": "Manyour"
  },
  {
    "id": "SC-002647",
    "type": "寄出",
    "country": "中国",
    "region": "湖北武汉",
    "note": "",
    "tags": [],
    "imgFront": "./images/SC-002647图像面.jpg",
    "sendDate": "2026-01-08",
    "receiveDate": "2026-01-11",
    "person": "虫耳朵",
    "platform": "Manyour"
  },
  {
    "id": "SC-002577",
    "type": "寄出",
    "country": "中国",
    "region": "黑龙江黑河",
    "note": "",
    "tags": [],
    "imgFront": "./images/SC-002577图像面.jpg",
    "sendDate": "2026-01-04",
    "receiveDate": "2026-01-11",
    "person": "影子与鸥",
    "platform": "Manyour"
  },
  {
    "id": "SC-002612",
    "type": "寄出",
    "country": "中国",
    "region": "广东汕头",
    "note": "",
    "tags": [],
    "imgFront": "./images/SC-002612图像面.jpg",
    "sendDate": "2026-01-06",
    "receiveDate": "2026-01-10",
    "person": "马",
    "platform": "Manyour"
  },
  {
    "id": "SC-002450",
    "type": "寄出",
    "country": "中国",
    "region": "陕西西安",
    "note": "",
    "tags": [],
    "imgFront": "./images/SC-002450图像面.jpg",
    "sendDate": "2025-12-21",
    "receiveDate": "2026-01-07",
    "person": "秦人集合",
    "platform": "Manyour"
  },
  {
    "id": "SC-002613",
    "type": "寄出",
    "country": "中国",
    "region": "湖北武汉",
    "note": "",
    "tags": [],
    "imgFront": "./images/SC-002613图像面.jpg",
    "sendDate": "2026-01-06",
    "receiveDate": "2026-01-10",
    "person": "楷特（林雪）",
    "platform": "Manyour"
  },
  {
    "id": "SC-002579",
    "type": "寄出",
    "country": "中国",
    "region": "山西运城",
    "note": "",
    "tags": [],
    "imgFront": "./images/SC-002579图像面.jpg",
    "sendDate": "2026-01-04",
    "receiveDate": "2026-01-08",
    "person": "鱼鱼鱼",
    "platform": "Manyour"
  },
  {
    "id": "SC-002581",
    "type": "寄出",
    "country": "中国",
    "region": "广东中山",
    "note": "",
    "tags": [],
    "imgFront": "./images/SC-002581图像面.jpg",
    "sendDate": "2026-01-04",
    "receiveDate": "2026-01-08",
    "person": "令狐冲",
    "platform": "Manyour"
  },
  {
    "id": "SC-002580",
    "type": "寄出",
    "country": "中国",
    "region": "广东广州",
    "note": "",
    "tags": [],
    "imgFront": "./images/SC-002580图像面.jpg",
    "sendDate": "2026-01-04",
    "receiveDate": "2026-01-08",
    "person": "利事醒宝",
    "platform": "Manyour"
  },
  {
    "id": "SC-002530",
    "type": "寄出",
    "country": "中国",
    "region": "四川成都",
    "note": "",
    "tags": [],
    "imgFront": "./images/SC-002530图像面.jpg",
    "sendDate": "2026-01-01",
    "receiveDate": "2026-01-06",
    "person": "ioi",
    "platform": "Manyour"
  },
  {
    "id": "SC-002390",
    "type": "寄出",
    "country": "中国",
    "region": "广东广州",
    "note": "",
    "tags": [],
    "imgFront": "./images/SC-002390图像面.jpg",
    "sendDate": "2025-12-14",
    "receiveDate": "2026-01-04",
    "person": "银河",
    "platform": "Manyour"
  },
  {
    "id": "SC-002453",
    "type": "寄出",
    "country": "中国",
    "region": "山东济南",
    "note": "",
    "tags": [],
    "imgFront": "./images/SC-002453图像面.jpg",
    "sendDate": "2025-12-21",
    "receiveDate": "2025-12-29",
    "person": "David_7",
    "platform": "Manyour"
  },
  {
    "id": "SC-002452",
    "type": "寄出",
    "country": "中国",
    "region": "江苏苏州",
    "note": "",
    "tags": [],
    "imgFront": "./images/SC-002452图像面.jpg",
    "sendDate": "2025-12-21",
    "receiveDate": "2025-12-27",
    "person": "麦田【空登必拉黑】",
    "platform": "Manyour"
  },
  {
    "id": "SC-002454",
    "type": "寄出",
    "country": "中国",
    "region": "辽宁大连",
    "note": "",
    "tags": [],
    "imgFront": "./images/SC-002454图像面.jpg",
    "sendDate": "2025-12-21",
    "receiveDate": "2025-12-27",
    "person": "茜茜(拒收盒片！！)",
    "platform": "Manyour"
  },
  {
    "id": "SC-002455",
    "type": "寄出",
    "country": "中国",
    "region": "浙江杭州",
    "note": "",
    "tags": [],
    "imgFront": "./images/SC-002455图像面.jpg",
    "sendDate": "2025-12-21",
    "receiveDate": "2025-12-25",
    "person": "Tsien",
    "platform": "Manyour"
  },
  {
    "id": "SC-002451",
    "type": "寄出",
    "country": "中国",
    "region": "黑龙江哈尔滨",
    "note": "",
    "tags": [],
    "imgFront": "./images/SC-002451图像面.jpg",
    "sendDate": "2025-12-21",
    "receiveDate": "2025-12-25",
    "person": "哈尔滨刘小美",
    "platform": "Manyour"
  },
  {
    "id": "SC-002412",
    "type": "寄出",
    "country": "中国",
    "region": "北京大兴区",
    "note": "",
    "tags": [],
    "imgFront": "./images/SC-002412图像面.jpg",
    "sendDate": "2025-12-16",
    "receiveDate": "2025-12-22",
    "person": "甜心",
    "platform": "Manyour"
  },
  {
    "id": "SC-002410",
    "type": "寄出",
    "country": "中国",
    "region": "上海松江区",
    "note": "",
    "tags": [],
    "imgFront": "./images/SC-002410图像面.jpg",
    "sendDate": "2025-12-16",
    "receiveDate": "2025-12-21",
    "person": "三文鱼茶茶",
    "platform": "Manyour"
  },
  {
    "id": "SC-002411",
    "type": "寄出",
    "country": "中国",
    "region": "广东中山",
    "note": "",
    "tags": [],
    "imgFront": "./images/SC-002411图像面.jpg",
    "sendDate": "2025-12-16",
    "receiveDate": "2025-12-21",
    "person": "令狐冲",
    "platform": "Manyour"
  },
  {
    "id": "ZJ-008521",
    "type": "收到",
    "country": "中国",
    "region": "浙江舟山",
    "note": "",
    "tags": [],
    "imgFront": "./images/ZJ-008521图像面.jpg",
    "sendDate": "2026-01-08",
    "receiveDate": "2026-01-14",
    "person": "禦",
    "platform": "Manyour"
  },
  {
    "id": "GD-015476",
    "type": "收到",
    "country": "中国",
    "region": "广东东莞",
    "note": "",
    "tags": [],
    "imgFront": "./images/GD-015476图像面.jpg",
    "sendDate": "2026-01-05",
    "receiveDate": "2026-01-12",
    "person": "七奈",
    "platform": "Manyour"
  },
  {
    "id": "JS-012633",
    "type": "收到",
    "country": "中国",
    "region": "江苏盐城",
    "note": "",
    "tags": [],
    "imgFront": "./images/JS-012633图像面.jpg",
    "sendDate": "2026-01-04",
    "receiveDate": "2026-01-11",
    "person": "孜行",
    "platform": "Manyour"
  },
  {
    "id": "HL-003041",
    "type": "收到",
    "country": "中国",
    "region": "黑龙江黑河",
    "note": "",
    "tags": [],
    "imgFront": "./images/HL-003041图像面.jpg",
    "sendDate": "2026-01-04",
    "receiveDate": "2026-01-11",
    "person": "影子与鸥",
    "platform": "Manyour"
  },
  {
    "id": "HB-003549",
    "type": "收到",
    "country": "中国",
    "region": "湖北武汉",
    "note": "",
    "tags": [],
    "imgFront": "./images/HB-003549图像面.jpg",
    "sendDate": "2026-01-04",
    "receiveDate": "2026-01-08",
    "person": "虫耳朵",
    "platform": "Manyour"
  },
  {
    "id": "JX-001448",
    "type": "收到",
    "country": "中国",
    "region": "江西九江",
    "note": "",
    "tags": [],
    "imgFront": "./images/JX-001448图像面.jpg",
    "sendDate": "2026-01-04",
    "receiveDate": "2026-01-08",
    "person": "小瑞",
    "platform": "Manyour"
  },
  {
    "id": "GZ-000373",
    "type": "收到",
    "country": "中国",
    "region": "贵州六盘水",
    "note": "",
    "tags": [],
    "imgFront": "./images/GZ-000373图像面.jpg",
    "sendDate": "2026-01-05",
    "receiveDate": "2026-01-08",
    "person": "小河",
    "platform": "Manyour"
  },
  {
    "id": "JS-012636",
    "type": "收到",
    "country": "中国",
    "region": "江苏南京",
    "note": "",
    "tags": [],
    "imgFront": "./images/JS-012636图像面.jpg",
    "sendDate": "2026-01-04",
    "receiveDate": "2026-01-08",
    "person": "朝歌",
    "platform": "Manyour"
  },
  {
    "id": "HL-002829",
    "type": "收到",
    "country": "中国",
    "region": "黑龙江齐齐哈尔",
    "note": "",
    "tags": [],
    "imgFront": "./images/HL-002829图像面.jpg",
    "sendDate": "2025-12-21",
    "receiveDate": "2026-01-05",
    "person": "西红柿",
    "platform": "Manyour"
  },
  {
    "id": "HE-002662",
    "type": "收到",
    "country": "中国",
    "region": "河北秦皇岛",
    "note": "",
    "tags": [],
    "imgFront": "./images/HE-002662图像面.jpg",
    "sendDate": "2025-12-23",
    "receiveDate": "2026-01-04",
    "person": "扎希德",
    "platform": "Manyour"
  },
  {
    "id": "SH-006336",
    "type": "收到",
    "country": "中国",
    "region": "上海市松江区",
    "note": "",
    "tags": [],
    "imgFront": "./images/SH-006336图像面.jpg",
    "sendDate": "2025-12-22",
    "receiveDate": "2026-01-04",
    "person": "三文鱼茶茶",
    "platform": "Manyour"
  },
  {
    "id": "SD-003615",
    "type": "收到",
    "country": "中国",
    "region": "山东济南",
    "note": "",
    "tags": [],
    "imgFront": "./images/SD-003615图像面.jpg",
    "sendDate": "2025-12-23",
    "receiveDate": "2026-01-04",
    "person": "David_7",
    "platform": "Manyour"
  },
  {
    "id": "JS-011921",
    "type": "收到",
    "country": "中国",
    "region": "江苏苏州",
    "note": "",
    "tags": [],
    "imgFront": "./images/JS-011921图像面.jpg",
    "sendDate": "2025-12-21",
    "receiveDate": "2026-01-04",
    "person": "麦田【空登必拉黑】",
    "platform": "Manyour"
  },
  {
    "id": "HE-002596",
    "type": "收到",
    "country": "中国",
    "region": "河北唐山",
    "note": "",
    "tags": [],
    "imgFront": "./images/HE-002596图像面.jpg",
    "sendDate": "2025-12-18",
    "receiveDate": "2026-01-04",
    "person": "TY0309",
    "platform": "Manyour"
  },
  {
    "id": "JS-011992",
    "type": "收到",
    "country": "中国",
    "region": "江苏苏州",
    "note": "",
    "tags": [],
    "imgFront": "./images/JS-011992图像面.jpg",
    "sendDate": "2025-12-22",
    "receiveDate": "2026-01-04",
    "person": "有丸没丸",
    "platform": "Manyour"
  },
  {
    "id": "BJ-009548",
    "type": "收到",
    "country": "中国",
    "region": "北京市大兴区",
    "note": "",
    "tags": [],
    "imgFront": "./images/BJ-009548图像面.jpg",
    "sendDate": "2025-12-24",
    "receiveDate": "2026-01-04",
    "person": "甜心",
    "platform": "Manyour"
  },
  {
    "id": "ZJ-007787",
    "type": "收到",
    "country": "中国",
    "region": "浙江杭州",
    "note": "",
    "tags": [],
    "imgFront": "./images/ZJ-007787图像面.jpg",
    "sendDate": "2025-12-22",
    "receiveDate": "2026-01-04",
    "person": "周围",
    "platform": "Manyour"
  },
  {
    "id": "SN-003378",
    "type": "收到",
    "country": "中国",
    "region": "陕西西安",
    "note": "",
    "tags": [],
    "imgFront": "./images/SN-003378图像面.jpg",
    "sendDate": "2025-12-24",
    "receiveDate": "2026-01-04",
    "person": "naomiusagram",
    "platform": "Manyour"
  },
  {
    "id": "HI-004547",
    "type": "收到",
    "country": "中国",
    "region": "海南琼海",
    "note": "",
    "tags": [],
    "imgFront": "./images/HI-004547图像面.jpg",
    "sendDate": "2025-12-21",
    "receiveDate": "2026-01-04",
    "person": "夜叔",
    "platform": "Manyour"
  },
  {
    "id": "HL-002833",
    "type": "收到",
    "country": "中国",
    "region": "黑龙江哈尔滨",
    "note": "",
    "tags": [],
    "imgFront": "./images/HL-002833图像面.jpg",
    "sendDate": "2025-12-22",
    "receiveDate": "2025-12-25",
    "person": "哈尔滨刘小美",
    "platform": "Manyour"
  },
  {
    "id": "GD-014390",
    "type": "收到",
    "country": "中国",
    "region": "广东中山",
    "note": "",
    "tags": [],
    "imgFront": "./images/GD-014390图像面.jpg",
    "sendDate": "2025-12-21",
    "receiveDate": "2025-12-25",
    "person": "令狐冲",
    "platform": "Manyour"
  },
  {
    "id": "BJ-009471",
    "type": "收到",
    "country": "中国",
    "region": "北京市房山区",
    "note": "",
    "tags": [],
    "imgFront": "./images/BJ-009471图像面.jpg",
    "sendDate": "2025-12-21",
    "receiveDate": "2025-12-24",
    "person": "蜜蜂（糊弄人的拉黑）",
    "platform": "Manyour"
  },
  {
    "id": "SN-003278",
    "type": "收到",
    "country": "中国",
    "region": "陕西西安",
    "note": "",
    "tags": [],
    "imgFront": "./images/SN-003278图像面.jpg",
    "sendDate": "2025-12-22",
    "receiveDate": "2025-12-24",
    "person": "秦人集合",
    "platform": "Manyour"
  },
  {
    "id": "ZJ-007771",
    "type": "收到",
    "country": "中国",
    "region": "浙江杭州",
    "note": "",
    "tags": [],
    "imgFront": "./images/ZJ-007771图像面.jpg",
    "sendDate": "2025-12-21",
    "receiveDate": "2025-12-24",
    "person": "酒吧驻唱哈士奇",
    "platform": "Manyour"
  },
  {
    "id": "JS-011204",
    "type": "收到",
    "country": "中国",
    "region": "江苏南通",
    "note": "",
    "tags": [],
    "imgFront": "./images/JS-011204图像面.jpg",
    "sendDate": "2025-12-09",
    "receiveDate": "2025-12-14",
    "person": "Fr",
    "platform": "Manyour"
  },
  {
    "id": "CNSC9908",
    "type": "寄出",
    "country": "中国",
    "region": "四川成都",
    "note": "",
    "tags": [],
    "imgFront": "./images/CNSC9908图像面.jpg",
    "sendDate": "2026-01-07",
    "receiveDate": "2026-01-12",
    "person": "归塘",
    "platform": "ICY"
  },
  {
    "id": "CNSC9907",
    "type": "寄出",
    "country": "中国",
    "region": "辽宁大连",
    "note": "",
    "tags": [],
    "imgFront": "./images/CNSC9907图像面.jpg",
    "sendDate": "2026-01-07",
    "receiveDate": "2026-01-13",
    "person": "蘑菇",
    "platform": "ICY"
  },
  {
    "id": "CNSC9906",
    "type": "寄出",
    "country": "中国",
    "region": "四川德阳",
    "note": "",
    "tags": [],
    "imgFront": "./images/CNSC9906图像面.jpg",
    "sendDate": "2026-01-07",
    "receiveDate": "2026-01-09",
    "person": "蜗牛飞来飞去",
    "platform": "ICY"
  },
  {
    "id": "CNSC9903",
    "type": "寄出",
    "country": "中国",
    "region": "四川德阳",
    "note": "",
    "tags": [],
    "imgFront": "./images/CNSC9903图像面.jpg",
    "sendDate": "2026-01-07",
    "receiveDate": "2026-01-09",
    "person": "蜗牛飞来飞去",
    "platform": "ICY"
  },
  {
    "id": "CNSC9902",
    "type": "寄出",
    "country": "中国",
    "region": "辽宁大连",
    "note": "",
    "tags": [],
    "imgFront": "./images/CNSC9902图像面.jpg",
    "sendDate": "2026-01-07",
    "receiveDate": "2026-01-13",
    "person": "蘑菇",
    "platform": "ICY"
  },
  {
    "id": "CNSC9846",
    "type": "寄出",
    "country": "中国",
    "region": "上海市松江区",
    "note": "",
    "tags": [],
    "imgFront": "./images/CNSC9846图像面.jpg",
    "sendDate": "2025-12-20",
    "receiveDate": "2025-12-28",
    "person": "三文鱼茶茶",
    "platform": "ICY"
  },{
  "id": "CN-4190216",
  "type": "寄出",
  "country": "德国",
  "region": "",
  "note": "第一张国际明信片，很开心",
  "tags": [],
  "imgFront": "./images/CN-4190216图像面.jpg",
  "sendDate": "2025-12-14",
  "receiveDate": "2026-01-10",
  "person": "	lemiet",
  "platform": "Postcrossing"
},{
  "id": "PHCNSC-1567",
  "type": "寄出",
  "country": "中国",
  "region": "黑龙江哈尔滨",
  "note": "",
  "tags": [
    "猫空，史努比"
  ],
  "imgFront": "./images/PHCNSC-1567图像面.jpg",
  "sendDate": "2026-01-12",
  "receiveDate": "2026-01-16",
   "person": "坑坑",
  "platform": "Post-Hi"
},{
  "id": "PHCNSC-1568",
  "type": "寄出",
  "country": "中国",
  "region": "山东济南",
  "note": "",
  "tags": [
    "猫空",
    "史努比"
  ],
  "imgFront": "./images/PHCNSC-1568图像面.jpg",
  "sendDate": "2026-01-12",
  "receiveDate": "2026-01-16",
  "person": "汤圆",
  "platform": "Post-Hi"
},{
  "id": "HB-003699",
  "type": "收到",
  "country": "中国",
  "region": "湖北武汉",
  "note": "",
  "tags": [],
  "imgFront": "./images/HB-003699图像面.jpg",
  "sendDate": "2026-01-10",
  "receiveDate": "2026-01-16",
  "person": "caia97",
  "platform": "Manyour"
},
{
  "id": "SD-003919",
  "type": "收到",
  "country": "中国",
  "region": "山东青岛",
  "note": "",
  "tags": [],
  "imgFront": "./images/SD-003919图像面.jpg",
  "sendDate": "2026-01-07",
  "receiveDate": "2026-01-16",
  "person": "LxhNolan",
  "platform": "Manyour"
},
{
  "id": "ZJ-008575",
  "type": "收到",
  "country": "中国",
  "region": "浙江宁波",
  "note": "",
  "tags": [],
  "imgFront": "./images/ZJ-008575图像面.jpg",
  "sendDate": "2026-01-11",
  "receiveDate": "2026-01-16",
  "person": "三益",
  "platform": "Manyour"
},
{
  "id": "PHCNSD-3069",
  "type": "收到",
  "country": "中国",
  "region": "山东济南",
  "note": "",
  "tags": [],
  "imgFront": "./images/PHCNSD-3069图像面.jpg",
  "sendDate": "2026-01-13",
  "receiveDate": "2026-01-16",
  "person": "茶茶丸",
  "platform": "Post-Hi"
},
{
  "id": "PHCNBJ-3169",
  "type": "收到",
  "country": "中国",
  "region": "北京市朝阳区",
  "note": "",
  "tags": [],
  "imgFront": "./images/PHCNBJ-3169图像面.jpg",
  "sendDate": "2026-01-13",
  "receiveDate": "2026-01-16",
  "person": "兔兔",
  "platform": "Post-Hi"
},
{
  "id": "PHCNXJ-0477",
  "type": "收到",
  "country": "中国",
  "region": "新疆若羌",
  "note": "",
  "tags": [],
  "imgFront": "./images/PHCNXJ-0477图像面.jpg",
  "sendDate": "2026-01-10",
  "receiveDate": "2026-01-16",
  "person": "点梦人（缓慢收寄中）",
  "platform": "Post-Hi"
},
{
  "id": "CNHN15249",
  "type": "收到",
  "country": "中国",
  "region": "湖南长沙",
  "note": "",
  "tags": [],
  "imgFront": "./images/CNHN15249图像面.jpg",
  "sendDate": "2026-01-10",
  "receiveDate": "2026-01-16",
  "person": "彧郁昱",
  "platform": "ICY"
},{
  "id": "PHCNFJ-2671",
  "type": "收到",
  "country": "中国",
  "region": "福建福州",
  "note": "",
  "tags": [],
  "imgFront": "./images/PHCNFJ-2671图像面.jpg",
  "sendDate": "2025-12-21",
  "receiveDate": "2025-12-23",
  "person": "月儿丫丫",
  "platform": "Post-Hi"
},{
  "id": "PHCNSC-1559",
  "type": "寄出",
  "country": "中国",
  "region": "新疆巴音郭楞蒙古自治州",
  "note": "",
  "tags": [],
  "imgFront": "./images/PHCNSC-1559图像面.jpg",
  "sendDate": "2026-01-12",
  "receiveDate": "2026-01-16",
  "person": "点梦人（缓慢收寄中）",
  "platform": "Post-Hi"
},{
  "id": "PHCNSC-1594",
  "type": "寄出",
  "country": "中国",
  "region": "吉林长春",
  "note": "",
  "tags": [],
  "imgFront": "./images/PHCNSC-1594图像面.jpg",
  "sendDate": "2026-01-17",
  "receiveDate": "2026-01-18",
  "person": "Ordinary",
  "platform": "Post-Hi"
},{
  "id": "SC-002660",
  "type": "寄出",
  "country": "中国",
  "region": "浙江杭州",
  "note": "",
  "tags": [],
  "imgFront": "./images/SC-002660图像面.jpg",
  "sendDate": "2026-01-09",
  "receiveDate": "2026-01-17",
  "person": "酒吧驻唱哈士奇",
  "platform": "Manyour"
},{
  "id": "SC-002649",
  "type": "寄出",
  "country": "中国",
  "region": "贵州六盘水",
  "note": "",
  "tags": [],
  "imgFront": "./images/SC-002649图像面.jpg",
  "sendDate": "2026-01-08",
  "receiveDate": "2026-01-18",
  "person": "小河",
  "platform": "Manyour"
},{
  "id": "PHCNSH-4188",
  "type": "收到",
  "country": "中国",
  "region": "上海市闵行区",
  "note": "",
  "tags": [],
  "imgFront": "./images/PHCNSH-4188图像面.jpg",
  "sendDate": "2026-01-10",
  "receiveDate": "2026-01-18",
  "person": "ahy",
  "platform": "Post-Hi"
},
{
  "id": "PHCNSH-4183",
  "type": "收到",
  "country": "中国",
  "region": "上海市闵行区",
  "note": "",
  "tags": [],
  "imgFront": "./images/PHCNSH-4183图像面.jpg",
  "sendDate": "2026-01-10",
  "receiveDate": "2026-01-18",
  "person": "ahy",
  "platform": "Post-Hi"
},{
  "id": "SC-002666",
  "type": "寄出",
  "country": "中国",
  "region": "江苏南京",
  "note": "",
  "tags": [],
  "imgFront": "./images/SC-002666图像面.jpg",
  "sendDate": "2026-01-09",
  "receiveDate": "2026-01-20",
  "person": "朝歌",
  "platform": "Manyour"
},
{
  "id": "HB-003852",
  "type": "收到",
  "country": "中国",
  "region": "湖北武汉",
  "note": "",
  "tags": [],
  "imgFront": "./images/HB-003852图像面.jpg",
  "sendDate": "2026-01-16",
  "receiveDate": "2026-01-20",
  "person": "虫耳朵",
  "platform": "Manyour"
},
{
  "id": "PHCNZJ-6231",
  "type": "收到",
  "country": "中国",
  "region": "浙江绍兴",
  "note": "",
  "tags": [],
  "imgFront": "./images/PHCNZJ-6231图像面.jpg",
  "sendDate": "2026-01-17",
  "receiveDate": "2026-01-20",
  "person": "F A xx",
  "platform": "Post-Hi"
},
{
  "id": "PHCNHB-2412",
  "type": "收到",
  "country": "中国",
  "region": "湖北武汉",
  "note": "",
  "tags": [],
  "imgFront": "./images/PHCNHB-2412图像面.jpg",
  "sendDate": "2026-01-15",
  "receiveDate": "2026-01-20",
  "person": "Silence",
  "platform": "Post-Hi"
},{
  "id": "PHCNSC-1543",
  "type": "寄出",
  "country": "中国",
  "region": "上海闵行区",
  "note": "",
  "tags": [],
  "imgFront": "./images/PHCNSC-1543图像面.jpg",
  "sendDate": "2026-01-10",
  "receiveDate": "2026-01-16",
  "person": "ahy",
  "platform": "Post-Hi"
},{
  "id": "PHCNSC-1592",
  "type": "寄出",
  "country": "中国",
  "region": "广东东莞",
  "note": "",
  "tags": [],
  "imgFront": "./images/PHCNSC-1592图像面.jpg",
  "sendDate": "2026-01-17",
  "receiveDate": "2026-01-20",
  "person": "礼一",
  "platform": "Post-Hi"
},{
  "id": "PYLS-0001",
  "type": "收到",
  "country": "中国",
  "region": "西藏拉萨",
  "note": "",
  "tags": [],
  "imgFront": "./images/PYLS-0001图像面.jpg",
  "sendDate": "2026-01-16",
  "receiveDate": "2026-01-18",
  "person": "文意",
  "platform": "自寄"
},{
  "id": "PHCNSC-1593",
  "type": "寄出",
  "country": "中国",
  "region": "上海普陀区",
  "note": "",
  "tags": [],
  "imgFront": "./images/PHCNSC-1593图像面.jpg",
  "sendDate": "2026-01-17",
  "receiveDate": "2026-01-20",
  "person": "宇智波派大星",
  "platform": "Post-Hi"
},{
  "id": "SC-2848",
  "type": "寄出",
  "country": "中国",
  "region": "山西晋城",
  "note": "",
  "tags": [],
  "imgFront": "./images/SC-2848图像面.jpg",
  "sendDate": "2026-01-18",
  "receiveDate": "2026-01-21",
  "person": "江南",
  "platform": "Manyour"
},{
  "id": "PHCNSC-1604",
  "type": "寄出",
  "country": "中国",
  "region": "北京东城区",
  "note": "",
  "tags": [],
  "imgFront": "./images/PHCNSC-1604图像面.jpg",
  "sendDate": "2026-01-19",
  "receiveDate": "2026-01-21",
  "person": "凉拌炒鸡蛋",
  "platform": "Post-Hi"
},{
  "id": "CNHL-4759",
  "type": "收到",
  "country": "中国",
  "region": "黑龙江七台河",
  "note": "",
  "tags": [],
  "imgFront": "./images/CNHL-4759图像面.jpg",
  "sendDate": "2026-01-12",
  "receiveDate": "2026-01-22",
  "person": "阿七",
  "platform": "ICY"
},{
  "id": "PHCNHI-0419",
  "type": "收到",
  "country": "中国",
  "region": "海南三亚",
  "note": "",
  "tags": [],
  "imgFront": "./images/PHCNHI-0419图像面.jpg",
  "sendDate": "2026-01-17",
  "receiveDate": "2026-01-22",
  "person": "坑坑",
  "platform": "Post-Hi"
},{
  "id": "PHCNSH-4260",
  "type": "收到",
  "country": "中国",
  "region": "上海闵行区",
  "note": "",
  "tags": [],
  "imgFront": "./images/PHCNSH-4260图像面.jpg",
  "sendDate": "2026-01-19",
  "receiveDate": "2026-01-22",
  "person": "ahy",
  "platform": "Post-Hi"
},{
  "id": "SC-002820",
  "type": "寄出",
  "country": "中国",
  "region": "广东东莞",
  "note": "",
  "tags": [],
  "imgFront": "./images/SC-002820图像面.jpg",
  "sendDate": "2026-01-16",
  "receiveDate": "2026-01-23",
  "person": "caia97",
  "platform": "Manyour"
},{
  "id": "SC-002825",
  "type": "寄出",
  "country": "中国",
  "region": "广东东莞",
  "note": "",
  "tags": [],
  "imgFront": "./images/SC-002825图像面.jpg",
  "sendDate": "2026-01-16",
  "receiveDate": "2026-01-22",
  "person": "caia97",
  "platform": "Manyour"
},
];